# Generated by Django 5.2.4 on 2025-09-02 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteDeEnvio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='propietario',
            name='correo_electronico',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='LogMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('error', 'Error')], max_length=10)),
                ('casa', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.lotedeenvio')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
